#! /bin/bash

set -e

for config in "" "--release"
do
    pushd kernel
    cargo build $config
    popd

    pushd cortex-m
    cargo build $config
    cargo build $config --example task_basic
    cargo build $config --example task_advanced
    popd
done
