name: Publish 

on:
  release:
    types: [ published ]

env:
  CARGO_TERM_COLOR: always
  CRATES_TOKEN: ${{ secrets.CRATES_TOKEN }}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cd kernel && cargo publish --token ${CRATES_TOKEN}
      - run: cd cortex-m && cargo publish --token ${CRATES_TOKEN}
