name: Publish 

on:
  release:
    types: [ published ]

env:
  CARGO_TERM_COLOR: always
  CRATES_TOKEN: ${{ secrets.CRATES_TOKEN }}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cd kernel && cargo login ${CRATES_TOKEN} && cargo publish
      - run: cd cortex-m && cargo login ${CRATES_TOKEN} && cargo publish
